export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#334f00",
        "surface-dim": "#121414",
        "on-tertiary-container": "#5b5a5a",
        "surface-bright": "#37393a",
        "surface-variant": "#333535",
        "surface-container-lowest": "#0c0f0f",
        "on-tertiary": "#313030",
        "surface": "#121414",
        "tertiary-fixed-dim": "#c9c6c5",
        "surface-tint": "#98da27",
        "secondary-fixed-dim": "#c8c6c5",
        "background": "#121414",
        "on-surface-variant": "#c2cab0",
        "on-secondary-fixed-variant": "#474746",
        "outline": "#8c947c",
        "smoked-glass": "rgba(26, 26, 26, 0.6)",
        "on-secondary": "#313030",
        "surface-container-high": "#282a2b",
        "on-secondary-fixed": "#1c1b1b",
        "nightvision-neon": "#A3E635",
        "primary": "#ccff80",
        "void-black": "#050505",
        "secondary": "#c8c6c5",
        "on-error": "#690005",
        "inverse-surface": "#e2e2e2",
        "inverse-primary": "#446900",
        "tertiary": "#f2eeed",
        "on-primary": "#213600",
        "surface-container-highest": "#333535",
        "error-container": "#93000a",
        "laser-glow": "rgba(163, 230, 53, 0.4)",
        "terminal-cyan": "#00F0FF",
        "alert-red": "#FF3B3B",
        "glass-stroke": "rgba(255, 255, 255, 0.1)",
        "secondary-container": "#474746",
        "on-secondary-container": "#b7b5b4",
        "tertiary-container": "#d5d2d1",
        "charcoal-titanium": "#1A1A1A",
        "tertiary-fixed": "#e5e2e1",
        "inverse-on-surface": "#2f3131",
        "secondary-fixed": "#e5e2e1",
        "outline-variant": "#424936",
        "on-tertiary-fixed-variant": "#474646",
        "on-error-container": "#ffdad6",
        "surface-container": "#1e2020",
        "primary-fixed-dim": "#98da27",
        "on-surface": "#e2e2e2",
        "on-primary-fixed": "#121f00",
        "on-tertiary-fixed": "#1c1b1b",
        "surface-container-low": "#1a1c1c",
        "primary-container": "#a3e635",
        "on-background": "#e2e2e2",
        "error": "#ffb4ab",
        "primary-fixed": "#b2f746",
        "on-primary-container": "#416400"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-sm": "0.5rem",
        "stack-md": "1.5rem",
        "grid-margin": "2rem",
        "stack-lg": "4rem",
        "gutter": "1.5rem",
        "panel-padding": "1.25rem",
        "unit": "4px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "display-hero": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-hero": ["72px", { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
