# Generated by Django 6.0.6 on 2026-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
                ('progress', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_bars', models.BooleanField(default=False)),
                ('custom_bottom', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VentureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('badge', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
                ('image', models.URLField(max_length=500)),
                ('uptime', models.CharField(max_length=20)),
                ('growth', models.CharField(max_length=20)),
                ('active_nodes', models.CharField(max_length=20)),
                ('action_text', models.CharField(max_length=50)),
            ],
        ),
    ]
