# Generated by Django 6.0.6 on 2026-07-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('metric', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Career Highlight',
                'verbose_name_plural': 'Career Highlights',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CEOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="RAM BAHADUR'S LEGACY // ROZIL THAPA", max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('quote', models.TextField(blank=True)),
                ('quote_author', models.CharField(default='— ROZIL THAPA', max_length=100)),
                ('biography_text', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('identity_verified', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CEO Profile',
                'verbose_name_plural': 'CEO Profiles',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education Records',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['order'],
            },
        ),
    ]
