# Generated by Django 6.0.6 on 2026-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
                ('stats_label', models.CharField(max_length=50)),
                ('stats_value', models.CharField(max_length=50)),
                ('stats_progress', models.CharField(max_length=50)),
                ('stats_glow', models.BooleanField(default=False)),
                ('last_mod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('res', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('span', models.CharField(max_length=50)),
            ],
        ),
    ]
