# Generated by Django 6.0.6 on 2026-07-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Image', max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('outlet', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('News', 'News'), ('Press Release', 'Press Release'), ('Interview', 'Interview'), ('Conference', 'Conference'), ('Publication', 'Publication'), ('Award', 'Award')], max_length=50)),
                ('summary', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('date', models.CharField(max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
