# Generated by Django 6.0.6 on 2026-07-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_galleryitem_mediaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivesHeaderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Assets & Portfolio', max_length=200)),
                ('description', models.TextField(default='A centralized repository of technological deployments, cinematic operations, and infrastructural engineering projects executed under the Rozil Thapa mandate.')),
                ('total_assets', models.CharField(default='142', max_length=50)),
                ('data_density', models.CharField(default='8.4PB', max_length=50)),
            ],
            options={
                'verbose_name': 'Archives Header Configuration',
                'verbose_name_plural': 'Archives Header Configuration',
            },
        ),
    ]
