# Generated by Django 6.0.6 on 2026-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
                ('access_level', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('icon', models.CharField(default='article', max_length=50)),
            ],
        ),
    ]
