# Generated by Django 6.0.6 on 2026-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVenture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venture_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('is_material_icon', models.BooleanField(default=False)),
                ('icon_color', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('mod', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('percentage', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=10)),
            ],
        ),
    ]
