# Generated by Django 6.0.6 on 2026-07-08 15:32

from django.db import migrations, models

def seed_navbar_links(apps, schema_editor):
    NavbarLink = apps.get_model('home', 'NavbarLink')
    links = [
        ("Overview", "/#overview", 10),
        ("About CEO", "/#about-ceo", 20),
        ("Leadership", "/#leadership", 30),
        ("Vision", "/#vision", 40),
        ("Achievements", "/#achievements", 50),
        ("Media", "/#media", 60),
        ("Gallery", "/#gallery", 70),
        ("Contact", "/#contact", 80),
    ]
    for label, url, order in links:
        NavbarLink.objects.get_or_create(label=label, defaults={"url": url, "order": order})

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_heroconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Navbar Link',
                'verbose_name_plural': 'Navbar Links',
                'ordering': ['order'],
            },
        ),
        migrations.RunPython(seed_navbar_links),
    ]
