# Generated by Django 6.0.6 on 2026-07-08 15:43

from django.db import migrations, models


def seed_vision_data(apps, schema_editor):
    VisionManifesto = apps.get_model('home', 'VisionManifesto')
    StrategicPillar = apps.get_model('home', 'StrategicPillar')
    NavbarLink = apps.get_model('home', 'NavbarLink')

    # Seed the Vision Manifesto singleton
    VisionManifesto.objects.get_or_create(
        id=1,
        defaults={
            'headline': 'VISION_MANIFESTO',
            'subtitle': 'ROZIL THAPA // THE VISION BEHIND NIGHTVISION',
            'main_text': 'Our core philosophy revolves around the transition from reactive privacy to proactive, intelligent environments. In a rapidly evolving world, operations must transcend simple recording—it must become a sentient layer of protection that anticipates needs and ensures absolute tranquility.',
            'founder_directive': 'Engineering systems that meet the increasing demands of a dynamic privacy landscape.',
            'roadmap_title': 'The Vision Roadmap',
            'roadmap_text': 'NightVision is not merely a product line—it is a blueprint for the future of global infrastructure. We are on a mission to become the worldwide architect of high-tech privacy ecosystems, integrating AI-driven analytics with impenetrable physical hardware.',
            'latency_value': '0.02ms',
            'accuracy_value': '99.9%',
        }
    )

    # Seed the 4 Strategic Pillars
    pillars = [
        ('router', 'SEAMLESS_INTEGRATION', 'Wi-Fi based plug and play deployment. Our architecture eliminates complex wiring, allowing for instantaneous operational operations setup.', 10),
        ('bolt', 'ADVANCED_FEATURES', 'Practical usage focused design. Every feature is engineered to serve a specific mission-critical purpose in real-world scenarios.', 20),
        ('shield', 'DURABLE_ENGINEERING', 'High-performance in extreme environments (-20°C to 50°C+). Ruggedized hardware built for perpetual operations under stress.', 30),
        ('lock', 'DATA_PROTECTION', 'Secured hardware/software stack. Proprietary protection protocols ensure your operations data remains your eyes only.', 40),
    ]
    for icon, title, description, order in pillars:
        StrategicPillar.objects.get_or_create(title=title, defaults={'icon': icon, 'description': description, 'order': order})

    # Update the Vision navbar link to point to /vision page
    NavbarLink.objects.filter(label='Vision').update(url='/vision')


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_navbarlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Material icon name, e.g. 'router'", max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Strategic Pillar',
                'verbose_name_plural': 'Strategic Pillars',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisionManifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='VISION_MANIFESTO', max_length=200)),
                ('subtitle', models.CharField(default='ROZIL THAPA // THE VISION BEHIND NIGHTVISION', max_length=300)),
                ('main_text', models.TextField(blank=True)),
                ('founder_directive', models.TextField(blank=True)),
                ('roadmap_title', models.CharField(blank=True, max_length=200)),
                ('roadmap_text', models.TextField(blank=True)),
                ('latency_value', models.CharField(default='0.02ms', max_length=50)),
                ('accuracy_value', models.CharField(default='99.9%', max_length=50)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='vision/')),
                ('monitor_image', models.ImageField(blank=True, null=True, upload_to='vision/')),
            ],
            options={
                'verbose_name': 'Vision Manifesto',
                'verbose_name_plural': 'Vision Manifesto',
            },
        ),
        migrations.RunPython(seed_vision_data),
    ]
