# Generated by Django 6.0.6 on 2026-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_strategicpillar_visionmanifesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('clearance', models.CharField(max_length=100)),
                ('tenure', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('uptime', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status_color', models.CharField(default='bg-nightvision-neon', max_length=50)),
                ('status_width', models.CharField(default='100%', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('has_shadow', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
