# Generated by Django 6.0.6 on 2026-07-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='THE_FOUNDER_PROTOCOL', max_length=200)),
                ('subtitle', models.CharField(default='INITIATE_BIOGRAPHY_SEQUENCE', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stats_years', models.CharField(default='6+', max_length=50)),
                ('stats_projects', models.CharField(default='500+', max_length=50)),
                ('stats_retention', models.CharField(default='98.5%', max_length=50)),
                ('signature_text', models.CharField(default='— ROZIL THAPA', max_length=100)),
            ],
            options={
                'verbose_name': 'About Brief',
                'verbose_name_plural': 'About Brief',
            },
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='button_1_text',
            field=models.CharField(default='VIEW_CORE_BRIEF', max_length=50),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='button_1_url',
            field=models.CharField(default='/about-ceo', max_length=200),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='button_2_text',
            field=models.CharField(default='CONNECT_NOW', max_length=50),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='button_2_url',
            field=models.CharField(default='/contact', max_length=200),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='subtitle',
            field=models.CharField(default='FOUNDER // BUILDER // VISIONARY', max_length=200),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='title',
            field=models.CharField(default='ROZIL THAPA', max_length=200),
        ),
    ]
